name: 3Dmol.js CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
  

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: 20
          cache: npm
      
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Test    
        run: npm test

      - name: Coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"      
        run: npm run cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

